---
apiVersion: v1
kind: Pod
metadata:
  name: net-checker
spec:
  containers:
  - name: net-checker
    image: quay.io/rcampos/net-checker:latest
    command: ["netChecker"]
    args: [":8080", ":8081"]
    env:
     - name: NODE_NAME
       valueFrom:
         fieldRef: 
           apiVersion: v1
           fieldPath: spec.nodeName
     - name: NAMESPACE
       valueFrom:
         fieldRef: 
           apiVersion: v1
           fieldPath: metadata.namespace
     - name: IMAGE_NAME
       value: quay.io/rcampos/net-checker:latest
  serviceAccount: net-checker
