---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: net-checker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: net-checker
rules:
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: net-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: net-checker
subjects:
  - kind: ServiceAccount
    name: net-checker
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: net-checker
rules:
  - apiGroups:
    - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: net-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: net-checker
subjects:
  - kind: ServiceAccount
    name: net-checker
